#!/usr/bin/env python3
"""Finalize an Agent Browser WebM recording into reviewable artifacts."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path


def run(cmd: list[str], *, stderr_path: Path | None = None) -> subprocess.CompletedProcess[str]:
    stderr = stderr_path.open("w") if stderr_path else subprocess.PIPE
    try:
        return subprocess.run(cmd, check=True, text=True, stdout=subprocess.PIPE, stderr=stderr)
    finally:
        if stderr_path:
            stderr.close()


def require_tool(name: str) -> str:
    path = shutil.which(name)
    if not path:
        raise SystemExit(f"Required tool not found: {name}")
    return path


def parse_layout(layout: str) -> int:
    try:
        cols, rows = (int(part) for part in layout.lower().split("x", 1))
    except ValueError as exc:
        raise SystemExit(f"Invalid storyboard layout: {layout}") from exc
    if cols < 1 or rows < 1:
        raise SystemExit(f"Invalid storyboard layout: {layout}")
    return cols * rows


def read_timeline(path: Path | None) -> dict[str, object] | None:
    if not path:
        return None
    path = path.expanduser().resolve()
    if not path.exists():
        return {"path": str(path), "exists": False}

    events: list[dict[str, object]] = []
    with path.open(encoding="utf-8") as timeline_file:
        for line_number, line in enumerate(timeline_file, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                events.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise SystemExit(f"Invalid JSONL in {path}:{line_number}: {exc}") from exc

    counts: dict[str, int] = {}
    for event in events:
        name = str(event.get("event", "unknown"))
        counts[name] = counts.get(name, 0) + 1

    return {
        "path": str(path),
        "exists": True,
        "event_count": len(events),
        "event_counts": counts,
        "first_event": events[0] if events else None,
        "last_event": events[-1] if events else None,
    }


def parse_blackdetect(path: Path) -> list[str]:
    if not path.exists():
        return []
    return [line.strip() for line in path.read_text(encoding="utf-8", errors="replace").splitlines() if "black_" in line]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, help="Input WebM recording from Agent Browser.")
    parser.add_argument("--output-dir", required=True, help="Directory for finalized artifacts.")
    parser.add_argument("--basename", default="browser-recording", help="Base filename for outputs.")
    parser.add_argument("--fps", type=int, default=10, help="Output MP4 frame rate.")
    parser.add_argument("--crf", type=int, default=20, help="libx264 CRF value.")
    parser.add_argument("--storyboard-fps", type=float, default=1.0, help="Storyboard sampling FPS.")
    parser.add_argument("--storyboard-width", type=int, default=540, help="Width of each storyboard tile.")
    parser.add_argument("--storyboard-layout", default="4x4", help="FFmpeg tile layout, e.g. 4x4.")
    parser.add_argument("--timeline", help="Optional timeline.jsonl generated by browser_recording_lib.sh.")
    parser.add_argument("--no-mov", action="store_true", help="Skip MOV copy.")
    args = parser.parse_args()

    ffmpeg = require_tool("ffmpeg")
    ffprobe = require_tool("ffprobe")

    input_path = Path(args.input).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    if not input_path.exists():
        raise SystemExit(f"Input recording does not exist: {input_path}")

    mp4_path = output_dir / f"{args.basename}.mp4"
    mov_path = output_dir / f"{args.basename}.mov"
    storyboard_dir = output_dir / "storyboard"
    storyboard_dir.mkdir(parents=True, exist_ok=True)
    ffprobe_path = output_dir / "ffprobe.json"
    blackdetect_path = output_dir / "blackdetect.log"
    manifest_path = output_dir / "finalize-manifest.json"

    run(
        [
            ffmpeg,
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-i",
            str(input_path),
            "-vf",
            f"fps={args.fps},format=yuv420p",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            str(args.crf),
            "-movflags",
            "+faststart",
            str(mp4_path),
        ]
    )

    mov_output: str | None = None
    if not args.no_mov:
        run([ffmpeg, "-hide_banner", "-loglevel", "error", "-y", "-i", str(mp4_path), "-c", "copy", str(mov_path)])
        mov_output = str(mov_path)

    for old_storyboard in storyboard_dir.glob(f"{args.basename}-storyboard-*.jpg"):
        old_storyboard.unlink()
    parse_layout(args.storyboard_layout)
    storyboard_pattern = storyboard_dir / f"{args.basename}-storyboard-%03d.jpg"
    run(
        [
            ffmpeg,
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-i",
            str(mp4_path),
            "-vf",
            f"fps={args.storyboard_fps},scale={args.storyboard_width}:-1,tile={args.storyboard_layout}",
            "-q:v",
            "3",
            str(storyboard_pattern),
        ]
    )
    storyboards = sorted(storyboard_dir.glob(f"{args.basename}-storyboard-*.jpg"))

    probe = run(
        [
            ffprobe,
            "-hide_banner",
            "-loglevel",
            "error",
            "-show_entries",
            "format=duration,size",
            "-show_entries",
            "stream=width,height,r_frame_rate,codec_name",
            "-of",
            "json",
            str(mp4_path),
        ]
    )
    ffprobe_path.write_text(probe.stdout)
    probe_payload = json.loads(probe.stdout)

    run(
        [
            ffmpeg,
            "-hide_banner",
            "-nostats",
            "-i",
            str(mp4_path),
            "-vf",
            "blackdetect=d=0.25:pix_th=0.10",
            "-an",
            "-f",
            "null",
            "-",
        ],
        stderr_path=blackdetect_path,
    )
    black_segments = parse_blackdetect(blackdetect_path)
    timeline_summary = read_timeline(Path(args.timeline) if args.timeline else None)

    manifest = {
        "input": str(input_path),
        "outputs": {
            "mp4": str(mp4_path),
            "mov": mov_output,
            "storyboard_dir": str(storyboard_dir),
            "storyboards": [str(path) for path in storyboards],
        },
        "checks": {
            "ffprobe": str(ffprobe_path),
            "probe": probe_payload,
            "blackdetect": str(blackdetect_path),
            "black_segments": black_segments,
            "timeline": timeline_summary,
        },
        "settings": {
            "fps": args.fps,
            "crf": args.crf,
            "storyboard_fps": args.storyboard_fps,
            "storyboard_width": args.storyboard_width,
            "storyboard_layout": args.storyboard_layout,
        },
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps(manifest, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
